/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockDto
 */
export interface BlockDto {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof BlockDto
     */
    data?: { [key: string]: any; };
}

/**
 * Check if a given object implements the BlockDto interface.
 */
export function instanceOfBlockDto(value: object): value is BlockDto {
    return true;
}

export function BlockDtoFromJSON(json: any): BlockDto {
    return BlockDtoFromJSONTyped(json, false);
}

export function BlockDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function BlockDtoToJSON(json: any): BlockDto {
    return BlockDtoToJSONTyped(json, false);
}

export function BlockDtoToJSONTyped(value?: BlockDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

