/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BranchRenameRequest
 */
export interface BranchRenameRequest {
    /**
     * 
     * @type {string}
     * @memberof BranchRenameRequest
     */
    newName: string;
}

/**
 * Check if a given object implements the BranchRenameRequest interface.
 */
export function instanceOfBranchRenameRequest(value: object): value is BranchRenameRequest {
    if (!('newName' in value) || value['newName'] === undefined) return false;
    return true;
}

export function BranchRenameRequestFromJSON(json: any): BranchRenameRequest {
    return BranchRenameRequestFromJSONTyped(json, false);
}

export function BranchRenameRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BranchRenameRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'newName': json['newName'],
    };
}

export function BranchRenameRequestToJSON(json: any): BranchRenameRequest {
    return BranchRenameRequestToJSONTyped(json, false);
}

export function BranchRenameRequestToJSONTyped(value?: BranchRenameRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newName': value['newName'],
    };
}

