/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BranchRenameResponse
 */
export interface BranchRenameResponse {
    /**
     * 
     * @type {number}
     * @memberof BranchRenameResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BranchRenameResponse
     */
    name?: string;
}

/**
 * Check if a given object implements the BranchRenameResponse interface.
 */
export function instanceOfBranchRenameResponse(value: object): value is BranchRenameResponse {
    return true;
}

export function BranchRenameResponseFromJSON(json: any): BranchRenameResponse {
    return BranchRenameResponseFromJSONTyped(json, false);
}

export function BranchRenameResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BranchRenameResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function BranchRenameResponseToJSON(json: any): BranchRenameResponse {
    return BranchRenameResponseToJSONTyped(json, false);
}

export function BranchRenameResponseToJSONTyped(value?: BranchRenameResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

