/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BranchCreateRequest
 */
export interface BranchCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof BranchCreateRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof BranchCreateRequest
     */
    fromCommitId?: number;
}

/**
 * Check if a given object implements the BranchCreateRequest interface.
 */
export function instanceOfBranchCreateRequest(value: object): value is BranchCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function BranchCreateRequestFromJSON(json: any): BranchCreateRequest {
    return BranchCreateRequestFromJSONTyped(json, false);
}

export function BranchCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BranchCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'fromCommitId': json['fromCommitId'] == null ? undefined : json['fromCommitId'],
    };
}

export function BranchCreateRequestToJSON(json: any): BranchCreateRequest {
    return BranchCreateRequestToJSONTyped(json, false);
}

export function BranchCreateRequestToJSONTyped(value?: BranchCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'fromCommitId': value['fromCommitId'],
    };
}

