/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BranchCreateResponse
 */
export interface BranchCreateResponse {
    /**
     * 
     * @type {number}
     * @memberof BranchCreateResponse
     */
    branchId?: number;
    /**
     * 
     * @type {number}
     * @memberof BranchCreateResponse
     */
    saveId?: number;
}

/**
 * Check if a given object implements the BranchCreateResponse interface.
 */
export function instanceOfBranchCreateResponse(value: object): value is BranchCreateResponse {
    return true;
}

export function BranchCreateResponseFromJSON(json: any): BranchCreateResponse {
    return BranchCreateResponseFromJSONTyped(json, false);
}

export function BranchCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BranchCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'branchId': json['branchId'] == null ? undefined : json['branchId'],
        'saveId': json['saveId'] == null ? undefined : json['saveId'],
    };
}

export function BranchCreateResponseToJSON(json: any): BranchCreateResponse {
    return BranchCreateResponseToJSONTyped(json, false);
}

export function BranchCreateResponseToJSONTyped(value?: BranchCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branchId': value['branchId'],
        'saveId': value['saveId'],
    };
}

