/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 인증코드 검증 응답
 * @export
 * @interface CodeCheckResponse
 */
export interface CodeCheckResponse {
    /**
     * 검증 완료를 나타내는 코드
     * @type {string}
     * @memberof CodeCheckResponse
     */
    passCode?: string;
}

/**
 * Check if a given object implements the CodeCheckResponse interface.
 */
export function instanceOfCodeCheckResponse(value: object): value is CodeCheckResponse {
    return true;
}

export function CodeCheckResponseFromJSON(json: any): CodeCheckResponse {
    return CodeCheckResponseFromJSONTyped(json, false);
}

export function CodeCheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeCheckResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'passCode': json['passCode'] == null ? undefined : json['passCode'],
    };
}

export function CodeCheckResponseToJSON(json: any): CodeCheckResponse {
    return CodeCheckResponseToJSONTyped(json, false);
}

export function CodeCheckResponseToJSONTyped(value?: CodeCheckResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'passCode': value['passCode'],
    };
}

