/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommitResponse
 */
export interface CommitResponse {
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof CommitResponse
     */
    content?: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the CommitResponse interface.
 */
export function instanceOfCommitResponse(value: object): value is CommitResponse {
    return true;
}

export function CommitResponseFromJSON(json: any): CommitResponse {
    return CommitResponseFromJSONTyped(json, false);
}

export function CommitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommitResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function CommitResponseToJSON(json: any): CommitResponse {
    return CommitResponseToJSONTyped(json, false);
}

export function CommitResponseToJSONTyped(value?: CommitResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

