/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompareMergeCommitResponse
 */
export interface CompareMergeCommitResponse {
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof CompareMergeCommitResponse
     */
    base?: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof CompareMergeCommitResponse
     */
    target?: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the CompareMergeCommitResponse interface.
 */
export function instanceOfCompareMergeCommitResponse(value: object): value is CompareMergeCommitResponse {
    return true;
}

export function CompareMergeCommitResponseFromJSON(json: any): CompareMergeCommitResponse {
    return CompareMergeCommitResponseFromJSONTyped(json, false);
}

export function CompareMergeCommitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompareMergeCommitResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'base': json['base'] == null ? undefined : json['base'],
        'target': json['target'] == null ? undefined : json['target'],
    };
}

export function CompareMergeCommitResponseToJSON(json: any): CompareMergeCommitResponse {
    return CompareMergeCommitResponseToJSONTyped(json, false);
}

export function CompareMergeCommitResponseToJSONTyped(value?: CompareMergeCommitResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base': value['base'],
        'target': value['target'],
    };
}

