/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCommitResponse
 */
export interface CreateCommitResponse {
    /**
     * 
     * @type {number}
     * @memberof CreateCommitResponse
     */
    id?: number;
}

/**
 * Check if a given object implements the CreateCommitResponse interface.
 */
export function instanceOfCreateCommitResponse(value: object): value is CreateCommitResponse {
    return true;
}

export function CreateCommitResponseFromJSON(json: any): CreateCommitResponse {
    return CreateCommitResponseFromJSONTyped(json, false);
}

export function CreateCommitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommitResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function CreateCommitResponseToJSON(json: any): CreateCommitResponse {
    return CreateCommitResponseToJSONTyped(json, false);
}

export function CreateCommitResponseToJSONTyped(value?: CreateCommitResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

