/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocCreateResponse
 */
export interface DocCreateResponse {
    /**
     * 
     * @type {number}
     * @memberof DocCreateResponse
     */
    id?: number;
}

/**
 * Check if a given object implements the DocCreateResponse interface.
 */
export function instanceOfDocCreateResponse(value: object): value is DocCreateResponse {
    return true;
}

export function DocCreateResponseFromJSON(json: any): DocCreateResponse {
    return DocCreateResponseFromJSONTyped(json, false);
}

export function DocCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function DocCreateResponseToJSON(json: any): DocCreateResponse {
    return DocCreateResponseToJSONTyped(json, false);
}

export function DocCreateResponseToJSONTyped(value?: DocCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

