/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocTitleUpdateResponse
 */
export interface DocTitleUpdateResponse {
    /**
     * 
     * @type {number}
     * @memberof DocTitleUpdateResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DocTitleUpdateResponse
     */
    title?: string;
    /**
     * 
     * @type {Date}
     * @memberof DocTitleUpdateResponse
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the DocTitleUpdateResponse interface.
 */
export function instanceOfDocTitleUpdateResponse(value: object): value is DocTitleUpdateResponse {
    return true;
}

export function DocTitleUpdateResponseFromJSON(json: any): DocTitleUpdateResponse {
    return DocTitleUpdateResponseFromJSONTyped(json, false);
}

export function DocTitleUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocTitleUpdateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function DocTitleUpdateResponseToJSON(json: any): DocTitleUpdateResponse {
    return DocTitleUpdateResponseToJSONTyped(json, false);
}

export function DocTitleUpdateResponseToJSONTyped(value?: DocTitleUpdateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

