/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocTitleRequest
 */
export interface DocTitleRequest {
    /**
     * 
     * @type {string}
     * @memberof DocTitleRequest
     */
    title: string;
}

/**
 * Check if a given object implements the DocTitleRequest interface.
 */
export function instanceOfDocTitleRequest(value: object): value is DocTitleRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function DocTitleRequestFromJSON(json: any): DocTitleRequest {
    return DocTitleRequestFromJSONTyped(json, false);
}

export function DocTitleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocTitleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
    };
}

export function DocTitleRequestToJSON(json: any): DocTitleRequest {
    return DocTitleRequestToJSONTyped(json, false);
}

export function DocTitleRequestToJSONTyped(value?: DocTitleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
    };
}

