/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorResponseHeadersAcceptLanguageInner
 */
export interface ErrorResponseHeadersAcceptLanguageInner {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersAcceptLanguageInner
     */
    range?: string;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponseHeadersAcceptLanguageInner
     */
    weight?: number;
}

/**
 * Check if a given object implements the ErrorResponseHeadersAcceptLanguageInner interface.
 */
export function instanceOfErrorResponseHeadersAcceptLanguageInner(value: object): value is ErrorResponseHeadersAcceptLanguageInner {
    return true;
}

export function ErrorResponseHeadersAcceptLanguageInnerFromJSON(json: any): ErrorResponseHeadersAcceptLanguageInner {
    return ErrorResponseHeadersAcceptLanguageInnerFromJSONTyped(json, false);
}

export function ErrorResponseHeadersAcceptLanguageInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseHeadersAcceptLanguageInner {
    if (json == null) {
        return json;
    }
    return {
        
        'range': json['range'] == null ? undefined : json['range'],
        'weight': json['weight'] == null ? undefined : json['weight'],
    };
}

export function ErrorResponseHeadersAcceptLanguageInnerToJSON(json: any): ErrorResponseHeadersAcceptLanguageInner {
    return ErrorResponseHeadersAcceptLanguageInnerToJSONTyped(json, false);
}

export function ErrorResponseHeadersAcceptLanguageInnerToJSONTyped(value?: ErrorResponseHeadersAcceptLanguageInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'range': value['range'],
        'weight': value['weight'],
    };
}

