/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DefaultHttpStatusCode } from './DefaultHttpStatusCode';
import {
    instanceOfDefaultHttpStatusCode,
    DefaultHttpStatusCodeFromJSON,
    DefaultHttpStatusCodeFromJSONTyped,
    DefaultHttpStatusCodeToJSON,
} from './DefaultHttpStatusCode';
import type { HttpStatus } from './HttpStatus';
import {
    instanceOfHttpStatus,
    HttpStatusFromJSON,
    HttpStatusFromJSONTyped,
    HttpStatusToJSON,
} from './HttpStatus';

/**
 * @type ErrorResponseStatusCode
 * 
 * @export
 */
export type ErrorResponseStatusCode = DefaultHttpStatusCode | HttpStatus;

export function ErrorResponseStatusCodeFromJSON(json: any): ErrorResponseStatusCode {
    return ErrorResponseStatusCodeFromJSONTyped(json, false);
}

export function ErrorResponseStatusCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseStatusCode {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfDefaultHttpStatusCode(json)) {
        return DefaultHttpStatusCodeFromJSONTyped(json, true);
    }
    if (instanceOfHttpStatus(json)) {
        return HttpStatusFromJSONTyped(json, true);
    }

    return {} as any;
}

export function ErrorResponseStatusCodeToJSON(json: any): any {
    return ErrorResponseStatusCodeToJSONTyped(json, false);
}

export function ErrorResponseStatusCodeToJSONTyped(value?: ErrorResponseStatusCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfDefaultHttpStatusCode(value)) {
        return DefaultHttpStatusCodeToJSON(value as DefaultHttpStatusCode);
    }
    if (instanceOfHttpStatus(value)) {
        return HttpStatusToJSON(value as HttpStatus);
    }

    return {};
}

