/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GraphEdgeDto
 */
export interface GraphEdgeDto {
    /**
     * 
     * @type {number}
     * @memberof GraphEdgeDto
     */
    from?: number;
    /**
     * 
     * @type {number}
     * @memberof GraphEdgeDto
     */
    to?: number;
}

/**
 * Check if a given object implements the GraphEdgeDto interface.
 */
export function instanceOfGraphEdgeDto(value: object): value is GraphEdgeDto {
    return true;
}

export function GraphEdgeDtoFromJSON(json: any): GraphEdgeDto {
    return GraphEdgeDtoFromJSONTyped(json, false);
}

export function GraphEdgeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphEdgeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'] == null ? undefined : json['from'],
        'to': json['to'] == null ? undefined : json['to'],
    };
}

export function GraphEdgeDtoToJSON(json: any): GraphEdgeDto {
    return GraphEdgeDtoToJSONTyped(json, false);
}

export function GraphEdgeDtoToJSONTyped(value?: GraphEdgeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from': value['from'],
        'to': value['to'],
    };
}

