/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
    PageableObjectToJSONTyped,
} from './PageableObject';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
    SortObjectToJSONTyped,
} from './SortObject';
import type { DocListResponse } from './DocListResponse';
import {
    DocListResponseFromJSON,
    DocListResponseFromJSONTyped,
    DocListResponseToJSON,
    DocListResponseToJSONTyped,
} from './DocListResponse';

/**
 * 
 * @export
 * @interface PageDocListResponse
 */
export interface PageDocListResponse {
    /**
     * 
     * @type {number}
     * @memberof PageDocListResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageDocListResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageDocListResponse
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {number}
     * @memberof PageDocListResponse
     */
    size?: number;
    /**
     * 
     * @type {Array<DocListResponse>}
     * @memberof PageDocListResponse
     */
    content?: Array<DocListResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageDocListResponse
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageDocListResponse
     */
    sort?: SortObject;
    /**
     * 
     * @type {number}
     * @memberof PageDocListResponse
     */
    numberOfElements?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageDocListResponse
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageDocListResponse
     */
    last?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageDocListResponse
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageDocListResponse interface.
 */
export function instanceOfPageDocListResponse(value: object): value is PageDocListResponse {
    return true;
}

export function PageDocListResponseFromJSON(json: any): PageDocListResponse {
    return PageDocListResponseFromJSONTyped(json, false);
}

export function PageDocListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageDocListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(DocListResponseFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : SortObjectFromJSON(json['sort']),
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageDocListResponseToJSON(json: any): PageDocListResponse {
    return PageDocListResponseToJSONTyped(json, false);
}

export function PageDocListResponseToJSONTyped(value?: PageDocListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(DocListResponseToJSON)),
        'number': value['number'],
        'sort': SortObjectToJSON(value['sort']),
        'numberOfElements': value['numberOfElements'],
        'first': value['first'],
        'last': value['last'],
        'empty': value['empty'],
    };
}

