/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
    PageableObjectToJSONTyped,
} from './PageableObject';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
    SortObjectToJSONTyped,
} from './SortObject';
import type { DocListSimpleResponse } from './DocListSimpleResponse';
import {
    DocListSimpleResponseFromJSON,
    DocListSimpleResponseFromJSONTyped,
    DocListSimpleResponseToJSON,
    DocListSimpleResponseToJSONTyped,
} from './DocListSimpleResponse';

/**
 * 
 * @export
 * @interface PageDocListSimpleResponse
 */
export interface PageDocListSimpleResponse {
    /**
     * 
     * @type {number}
     * @memberof PageDocListSimpleResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageDocListSimpleResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageDocListSimpleResponse
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {number}
     * @memberof PageDocListSimpleResponse
     */
    size?: number;
    /**
     * 
     * @type {Array<DocListSimpleResponse>}
     * @memberof PageDocListSimpleResponse
     */
    content?: Array<DocListSimpleResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageDocListSimpleResponse
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageDocListSimpleResponse
     */
    sort?: SortObject;
    /**
     * 
     * @type {number}
     * @memberof PageDocListSimpleResponse
     */
    numberOfElements?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageDocListSimpleResponse
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageDocListSimpleResponse
     */
    last?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageDocListSimpleResponse
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageDocListSimpleResponse interface.
 */
export function instanceOfPageDocListSimpleResponse(value: object): value is PageDocListSimpleResponse {
    return true;
}

export function PageDocListSimpleResponseFromJSON(json: any): PageDocListSimpleResponse {
    return PageDocListSimpleResponseFromJSONTyped(json, false);
}

export function PageDocListSimpleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageDocListSimpleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(DocListSimpleResponseFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : SortObjectFromJSON(json['sort']),
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageDocListSimpleResponseToJSON(json: any): PageDocListSimpleResponse {
    return PageDocListSimpleResponseToJSONTyped(json, false);
}

export function PageDocListSimpleResponseToJSONTyped(value?: PageDocListSimpleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(DocListSimpleResponseToJSON)),
        'number': value['number'],
        'sort': SortObjectToJSON(value['sort']),
        'numberOfElements': value['numberOfElements'],
        'first': value['first'],
        'last': value['last'],
        'empty': value['empty'],
    };
}

