/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 비밀번호 변경용 인증코드 요청 DTO
 * @export
 * @interface PwdResetCodeRequest
 */
export interface PwdResetCodeRequest {
    /**
     * 이메일 주소
     * @type {string}
     * @memberof PwdResetCodeRequest
     */
    email: string;
}

/**
 * Check if a given object implements the PwdResetCodeRequest interface.
 */
export function instanceOfPwdResetCodeRequest(value: object): value is PwdResetCodeRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function PwdResetCodeRequestFromJSON(json: any): PwdResetCodeRequest {
    return PwdResetCodeRequestFromJSONTyped(json, false);
}

export function PwdResetCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PwdResetCodeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function PwdResetCodeRequestToJSON(json: any): PwdResetCodeRequest {
    return PwdResetCodeRequestToJSONTyped(json, false);
}

export function PwdResetCodeRequestToJSONTyped(value?: PwdResetCodeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

