/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecentActivityDto
 */
export interface RecentActivityDto {
    /**
     * 
     * @type {string}
     * @memberof RecentActivityDto
     */
    recentType?: RecentActivityDtoRecentTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof RecentActivityDto
     */
    recentTypeId?: number;
}


/**
 * @export
 */
export const RecentActivityDtoRecentTypeEnum = {
    Save: 'SAVE',
    Commit: 'COMMIT'
} as const;
export type RecentActivityDtoRecentTypeEnum = typeof RecentActivityDtoRecentTypeEnum[keyof typeof RecentActivityDtoRecentTypeEnum];


/**
 * Check if a given object implements the RecentActivityDto interface.
 */
export function instanceOfRecentActivityDto(value: object): value is RecentActivityDto {
    return true;
}

export function RecentActivityDtoFromJSON(json: any): RecentActivityDto {
    return RecentActivityDtoFromJSONTyped(json, false);
}

export function RecentActivityDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecentActivityDto {
    if (json == null) {
        return json;
    }
    return {
        
        'recentType': json['recentType'] == null ? undefined : json['recentType'],
        'recentTypeId': json['recentTypeId'] == null ? undefined : json['recentTypeId'],
    };
}

export function RecentActivityDtoToJSON(json: any): RecentActivityDto {
    return RecentActivityDtoToJSONTyped(json, false);
}

export function RecentActivityDtoToJSONTyped(value?: RecentActivityDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recentType': value['recentType'],
        'recentTypeId': value['recentTypeId'],
    };
}

