/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveGetResponse
 */
export interface SaveGetResponse {
    /**
     * 
     * @type {Date}
     * @memberof SaveGetResponse
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof SaveGetResponse
     */
    content?: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the SaveGetResponse interface.
 */
export function instanceOfSaveGetResponse(value: object): value is SaveGetResponse {
    return true;
}

export function SaveGetResponseFromJSON(json: any): SaveGetResponse {
    return SaveGetResponseFromJSONTyped(json, false);
}

export function SaveGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveGetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function SaveGetResponseToJSON(json: any): SaveGetResponse {
    return SaveGetResponseToJSONTyped(json, false);
}

export function SaveGetResponseToJSONTyped(value?: SaveGetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'content': value['content'],
    };
}

