/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveBlock
 */
export interface SaveBlock {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SaveBlock
     */
    data?: { [key: string]: any; };
}

/**
 * Check if a given object implements the SaveBlock interface.
 */
export function instanceOfSaveBlock(value: object): value is SaveBlock {
    return true;
}

export function SaveBlockFromJSON(json: any): SaveBlock {
    return SaveBlockFromJSONTyped(json, false);
}

export function SaveBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveBlock {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function SaveBlockToJSON(json: any): SaveBlock {
    return SaveBlockToJSONTyped(json, false);
}

export function SaveBlockToJSONTyped(value?: SaveBlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

