/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveUpdateResponse
 */
export interface SaveUpdateResponse {
    /**
     * 
     * @type {Date}
     * @memberof SaveUpdateResponse
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the SaveUpdateResponse interface.
 */
export function instanceOfSaveUpdateResponse(value: object): value is SaveUpdateResponse {
    return true;
}

export function SaveUpdateResponseFromJSON(json: any): SaveUpdateResponse {
    return SaveUpdateResponseFromJSONTyped(json, false);
}

export function SaveUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveUpdateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function SaveUpdateResponseToJSON(json: any): SaveUpdateResponse {
    return SaveUpdateResponseToJSONTyped(json, false);
}

export function SaveUpdateResponseToJSONTyped(value?: SaveUpdateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

