/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveUpdateRequest
 */
export interface SaveUpdateRequest {
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof SaveUpdateRequest
     */
    content?: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the SaveUpdateRequest interface.
 */
export function instanceOfSaveUpdateRequest(value: object): value is SaveUpdateRequest {
    return true;
}

export function SaveUpdateRequestFromJSON(json: any): SaveUpdateRequest {
    return SaveUpdateRequestFromJSONTyped(json, false);
}

export function SaveUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function SaveUpdateRequestToJSON(json: any): SaveUpdateRequest {
    return SaveUpdateRequestToJSONTyped(json, false);
}

export function SaveUpdateRequestToJSONTyped(value?: SaveUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

