/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 세션 유효성 확인 응답
 * @export
 * @interface SessionCheckResponse
 */
export interface SessionCheckResponse {
    /**
     * 로그인 상태의 사용자 ID
     * @type {number}
     * @memberof SessionCheckResponse
     */
    id?: number;
    /**
     * 로그인 상태의 사용자 이름
     * @type {string}
     * @memberof SessionCheckResponse
     */
    name?: string;
}

/**
 * Check if a given object implements the SessionCheckResponse interface.
 */
export function instanceOfSessionCheckResponse(value: object): value is SessionCheckResponse {
    return true;
}

export function SessionCheckResponseFromJSON(json: any): SessionCheckResponse {
    return SessionCheckResponseFromJSONTyped(json, false);
}

export function SessionCheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionCheckResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function SessionCheckResponseToJSON(json: any): SessionCheckResponse {
    return SessionCheckResponseToJSONTyped(json, false);
}

export function SessionCheckResponseToJSONTyped(value?: SessionCheckResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

