/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 회원가입용 인증코드 요청
 * @export
 * @interface SignupCodeRequest
 */
export interface SignupCodeRequest {
    /**
     * 이메일 주소
     * @type {string}
     * @memberof SignupCodeRequest
     */
    email: string;
}

/**
 * Check if a given object implements the SignupCodeRequest interface.
 */
export function instanceOfSignupCodeRequest(value: object): value is SignupCodeRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function SignupCodeRequestFromJSON(json: any): SignupCodeRequest {
    return SignupCodeRequestFromJSONTyped(json, false);
}

export function SignupCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupCodeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function SignupCodeRequestToJSON(json: any): SignupCodeRequest {
    return SignupCodeRequestToJSONTyped(json, false);
}

export function SignupCodeRequestToJSONTyped(value?: SignupCodeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

