/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 회원가입 요청
 * @export
 * @interface UserSignupRequest
 */
export interface UserSignupRequest {
    /**
     * 회원 이름
     * @type {string}
     * @memberof UserSignupRequest
     */
    name: string;
    /**
     * 이메일 주소
     * @type {string}
     * @memberof UserSignupRequest
     */
    email: string;
    /**
     * 비밀번호 (대소문자+숫자 조합 8자 이상)
     * @type {string}
     * @memberof UserSignupRequest
     */
    password: string;
    /**
     * 검증 완료를 나타내는 코드
     * @type {string}
     * @memberof UserSignupRequest
     */
    passCode: string;
}

/**
 * Check if a given object implements the UserSignupRequest interface.
 */
export function instanceOfUserSignupRequest(value: object): value is UserSignupRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('passCode' in value) || value['passCode'] === undefined) return false;
    return true;
}

export function UserSignupRequestFromJSON(json: any): UserSignupRequest {
    return UserSignupRequestFromJSONTyped(json, false);
}

export function UserSignupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSignupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'password': json['password'],
        'passCode': json['passCode'],
    };
}

export function UserSignupRequestToJSON(json: any): UserSignupRequest {
    return UserSignupRequestToJSONTyped(json, false);
}

export function UserSignupRequestToJSONTyped(value?: UserSignupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'password': value['password'],
        'passCode': value['passCode'],
    };
}

