/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 회원가입 응답
 * @export
 * @interface UserSignupResponse
 */
export interface UserSignupResponse {
    /**
     * 가입한 사용자 ID
     * @type {number}
     * @memberof UserSignupResponse
     */
    id?: number;
    /**
     * 가입된 사용자 이름
     * @type {string}
     * @memberof UserSignupResponse
     */
    name?: string;
}

/**
 * Check if a given object implements the UserSignupResponse interface.
 */
export function instanceOfUserSignupResponse(value: object): value is UserSignupResponse {
    return true;
}

export function UserSignupResponseFromJSON(json: any): UserSignupResponse {
    return UserSignupResponseFromJSONTyped(json, false);
}

export function UserSignupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSignupResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function UserSignupResponseToJSON(json: any): UserSignupResponse {
    return UserSignupResponseToJSONTyped(json, false);
}

export function UserSignupResponseToJSONTyped(value?: UserSignupResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

