/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CodeCheckRequest,
  CodeCheckResponse,
  ErrorResponse,
  PwdResetCodeRequest,
  SessionCheckResponse,
  SignupCodeRequest,
} from '../models/index';
import {
    CodeCheckRequestFromJSON,
    CodeCheckRequestToJSON,
    CodeCheckResponseFromJSON,
    CodeCheckResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    PwdResetCodeRequestFromJSON,
    PwdResetCodeRequestToJSON,
    SessionCheckResponseFromJSON,
    SessionCheckResponseToJSON,
    SignupCodeRequestFromJSON,
    SignupCodeRequestToJSON,
} from '../models/index';

export interface CheckCodeRequest {
    codeCheckRequest: CodeCheckRequest;
}

export interface SendResetPwdCodeRequest {
    pwdResetCodeRequest: PwdResetCodeRequest;
}

export interface SendSignupCodeRequest {
    signupCodeRequest: SignupCodeRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * 이메일, 인증코드, 코드 타입(SIGNUP / RESET_PASSWORD)을 입력받아 인증코드의 유효성을 검증합니다. 인증코드는 일정 시간 동안만 유효합니다. 잘못된 코드, 만료된 코드, 시스템 에러 발생 시 각기 다른 응답이 반환됩니다. 
     * 인증코드 검증
     */
    async checkCodeRaw(requestParameters: CheckCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CodeCheckResponse>> {
        if (requestParameters['codeCheckRequest'] == null) {
            throw new runtime.RequiredError(
                'codeCheckRequest',
                'Required parameter "codeCheckRequest" was null or undefined when calling checkCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/auth/code/check`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CodeCheckRequestToJSON(requestParameters['codeCheckRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CodeCheckResponseFromJSON(jsonValue));
    }

    /**
     * 이메일, 인증코드, 코드 타입(SIGNUP / RESET_PASSWORD)을 입력받아 인증코드의 유효성을 검증합니다. 인증코드는 일정 시간 동안만 유효합니다. 잘못된 코드, 만료된 코드, 시스템 에러 발생 시 각기 다른 응답이 반환됩니다. 
     * 인증코드 검증
     */
    async checkCode(requestParameters: CheckCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CodeCheckResponse> {
        const response = await this.checkCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 현재 로그인된 사용자의 세션이 유효한지 확인하고 사용자 정보를 반환합니다.
     * 세션 유효성 확인
     */
    async checkSessionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionCheckResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/auth/session/check`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionCheckResponseFromJSON(jsonValue));
    }

    /**
     * 현재 로그인된 사용자의 세션이 유효한지 확인하고 사용자 정보를 반환합니다.
     * 세션 유효성 확인
     */
    async checkSession(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionCheckResponse> {
        const response = await this.checkSessionRaw(initOverrides);
        return await response.value();
    }

    /**
     * 사용자가 입력한 이메일 주소로 비밀번호 재설정을 위한 인증코드를 전송합니다. 해당 이메일이 등록된 사용자 계정이어야 하며, 인증코드는 일정 시간 동안 유효합니다. 존재하지 않는 사용자에게 요청 시 에러가 발생합니다. 
     * 비밀번호 변경 인증코드 전송
     */
    async sendResetPwdCodeRaw(requestParameters: SendResetPwdCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['pwdResetCodeRequest'] == null) {
            throw new runtime.RequiredError(
                'pwdResetCodeRequest',
                'Required parameter "pwdResetCodeRequest" was null or undefined when calling sendResetPwdCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/auth/code/reset-password`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PwdResetCodeRequestToJSON(requestParameters['pwdResetCodeRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 사용자가 입력한 이메일 주소로 비밀번호 재설정을 위한 인증코드를 전송합니다. 해당 이메일이 등록된 사용자 계정이어야 하며, 인증코드는 일정 시간 동안 유효합니다. 존재하지 않는 사용자에게 요청 시 에러가 발생합니다. 
     * 비밀번호 변경 인증코드 전송
     */
    async sendResetPwdCode(requestParameters: SendResetPwdCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.sendResetPwdCodeRaw(requestParameters, initOverrides);
    }

    /**
     * 사용자가 입력한 이메일 주소로 회원가입을 위한 인증코드를 전송합니다. 인증코드는 이메일로 전송되며, 제한된 시간(3분) 내에 입력되어야 합니다. 이미 가입된 이메일 주소로 요청하는 경우 에러가 발생합니다. 
     * 회원가입 인증코드 전송
     */
    async sendSignupCodeRaw(requestParameters: SendSignupCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['signupCodeRequest'] == null) {
            throw new runtime.RequiredError(
                'signupCodeRequest',
                'Required parameter "signupCodeRequest" was null or undefined when calling sendSignupCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/auth/code/signup-email`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignupCodeRequestToJSON(requestParameters['signupCodeRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 사용자가 입력한 이메일 주소로 회원가입을 위한 인증코드를 전송합니다. 인증코드는 이메일로 전송되며, 제한된 시간(3분) 내에 입력되어야 합니다. 이미 가입된 이메일 주소로 요청하는 경우 에러가 발생합니다. 
     * 회원가입 인증코드 전송
     */
    async sendSignupCode(requestParameters: SendSignupCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.sendSignupCodeRaw(requestParameters, initOverrides);
    }

}
