/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommitGraphResponse,
  DocCreateResponse,
  DocTitleRequest,
  DocTitleUpdateResponse,
  PageDocListResponse,
  PageDocListSimpleResponse,
} from '../models/index';
import {
    CommitGraphResponseFromJSON,
    CommitGraphResponseToJSON,
    DocCreateResponseFromJSON,
    DocCreateResponseToJSON,
    DocTitleRequestFromJSON,
    DocTitleRequestToJSON,
    DocTitleUpdateResponseFromJSON,
    DocTitleUpdateResponseToJSON,
    PageDocListResponseFromJSON,
    PageDocListResponseToJSON,
    PageDocListSimpleResponseFromJSON,
    PageDocListSimpleResponseToJSON,
} from '../models/index';

export interface DeleteRequest {
    docId: number;
    userId: number;
}

export interface CreateRequest {
    docTitleRequest: DocTitleRequest;
}

export interface GetGraphRequest {
    docId: number;
}

export interface ReadListRequest {
    sort?: string;
    order?: string;
    page?: number;
    size?: number;
}

export interface ReadListSidebarRequest {
    sort?: string;
    order?: string;
    page?: number;
    size?: number;
}

export interface UpdateDocumentTitleRequest {
    docId: number;
    docTitleRequest: DocTitleRequest;
}

/**
 * 
 */
export class DocControllerApi extends runtime.BaseAPI {

    /**
     */
    async _deleteRaw(requestParameters: DeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['docId'] == null) {
            throw new runtime.RequiredError(
                'docId',
                'Required parameter "docId" was null or undefined when calling _delete().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling _delete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/document/{docId}`;
        urlPath = urlPath.replace(`{${"docId"}}`, encodeURIComponent(String(requestParameters['docId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async _delete(requestParameters: DeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this._deleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createRaw(requestParameters: CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DocCreateResponse>> {
        if (requestParameters['docTitleRequest'] == null) {
            throw new runtime.RequiredError(
                'docTitleRequest',
                'Required parameter "docTitleRequest" was null or undefined when calling create().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/document`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DocTitleRequestToJSON(requestParameters['docTitleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DocCreateResponseFromJSON(jsonValue));
    }

    /**
     */
    async create(requestParameters: CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DocCreateResponse> {
        const response = await this.createRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getGraphRaw(requestParameters: GetGraphRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommitGraphResponse>> {
        if (requestParameters['docId'] == null) {
            throw new runtime.RequiredError(
                'docId',
                'Required parameter "docId" was null or undefined when calling getGraph().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/document/{docId}/graph`;
        urlPath = urlPath.replace(`{${"docId"}}`, encodeURIComponent(String(requestParameters['docId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommitGraphResponseFromJSON(jsonValue));
    }

    /**
     */
    async getGraph(requestParameters: GetGraphRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommitGraphResponse> {
        const response = await this.getGraphRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async readListRaw(requestParameters: ReadListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageDocListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/document`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageDocListResponseFromJSON(jsonValue));
    }

    /**
     */
    async readList(requestParameters: ReadListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageDocListResponse> {
        const response = await this.readListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async readListSidebarRaw(requestParameters: ReadListSidebarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageDocListSimpleResponse>> {
        const queryParameters: any = {};

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/document/sidebar`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageDocListSimpleResponseFromJSON(jsonValue));
    }

    /**
     */
    async readListSidebar(requestParameters: ReadListSidebarRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageDocListSimpleResponse> {
        const response = await this.readListSidebarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateDocumentTitleRaw(requestParameters: UpdateDocumentTitleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DocTitleUpdateResponse>> {
        if (requestParameters['docId'] == null) {
            throw new runtime.RequiredError(
                'docId',
                'Required parameter "docId" was null or undefined when calling updateDocumentTitle().'
            );
        }

        if (requestParameters['docTitleRequest'] == null) {
            throw new runtime.RequiredError(
                'docTitleRequest',
                'Required parameter "docTitleRequest" was null or undefined when calling updateDocumentTitle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/document/{docId}`;
        urlPath = urlPath.replace(`{${"docId"}}`, encodeURIComponent(String(requestParameters['docId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: DocTitleRequestToJSON(requestParameters['docTitleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DocTitleUpdateResponseFromJSON(jsonValue));
    }

    /**
     */
    async updateDocumentTitle(requestParameters: UpdateDocumentTitleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DocTitleUpdateResponse> {
        const response = await this.updateDocumentTitleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
