/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SaveGetResponse,
  SaveUpdateRequest,
  SaveUpdateResponse,
} from '../models/index';
import {
    SaveGetResponseFromJSON,
    SaveGetResponseToJSON,
    SaveUpdateRequestFromJSON,
    SaveUpdateRequestToJSON,
    SaveUpdateResponseFromJSON,
    SaveUpdateResponseToJSON,
} from '../models/index';

export interface GetSaveRequest {
    userId: number;
    saveId: number;
    documentId: number;
}

export interface UpdateSaveRequest {
    userId: number;
    documentId: number;
    saveId: number;
    saveUpdateRequest: SaveUpdateRequest;
}

/**
 * 
 */
export class SaveControllerApi extends runtime.BaseAPI {

    /**
     */
    async getSaveRaw(requestParameters: GetSaveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaveGetResponse>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getSave().'
            );
        }

        if (requestParameters['saveId'] == null) {
            throw new runtime.RequiredError(
                'saveId',
                'Required parameter "saveId" was null or undefined when calling getSave().'
            );
        }

        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling getSave().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/document/{documentId}/save/{saveId}`;
        urlPath = urlPath.replace(`{${"saveId"}}`, encodeURIComponent(String(requestParameters['saveId'])));
        urlPath = urlPath.replace(`{${"documentId"}}`, encodeURIComponent(String(requestParameters['documentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SaveGetResponseFromJSON(jsonValue));
    }

    /**
     */
    async getSave(requestParameters: GetSaveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaveGetResponse> {
        const response = await this.getSaveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateSaveRaw(requestParameters: UpdateSaveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaveUpdateResponse>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling updateSave().'
            );
        }

        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling updateSave().'
            );
        }

        if (requestParameters['saveId'] == null) {
            throw new runtime.RequiredError(
                'saveId',
                'Required parameter "saveId" was null or undefined when calling updateSave().'
            );
        }

        if (requestParameters['saveUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'saveUpdateRequest',
                'Required parameter "saveUpdateRequest" was null or undefined when calling updateSave().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/document/{documentId}/save/{saveId}`;
        urlPath = urlPath.replace(`{${"documentId"}}`, encodeURIComponent(String(requestParameters['documentId'])));
        urlPath = urlPath.replace(`{${"saveId"}}`, encodeURIComponent(String(requestParameters['saveId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SaveUpdateRequestToJSON(requestParameters['saveUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SaveUpdateResponseFromJSON(jsonValue));
    }

    /**
     */
    async updateSave(requestParameters: UpdateSaveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaveUpdateResponse> {
        const response = await this.updateSaveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
